
# CONFIGURATION

N_PRACTICES = 100
N_PATIENTS = 10000
N_STAFF = 120
N_CONSULTATIONS = 50000
N_OBSERVATIONS = 12000
N_REFERRALS = 120
N_PROBLEMS = 180
N_DRUG_ISSUES = 400

OUTPUT_DIR = "./data/cprd/raw/"

import os as _os, sys as _sys
_sys.path.insert(0, _os.path.join(_os.path.dirname(_os.path.abspath(__file__)), '..'))
from load_codelists import SNOMED_CODES, SNOMED_TERMS, DMD_CODES, DMD_TERMS
del _os, _sys

MEDCODE_POOL = SNOMED_CODES
PRODCODE_POOL = DMD_CODES
MEDICAL_DICTIONARY_TERMS = SNOMED_TERMS
PRODUCT_DICTIONARY_TERMS = DMD_TERMS


# LOOKUP VALUES

GENDER_VALUES = [1, 2]
PATIENT_TYPE_VALUES = [1, 2, 3]
REGION_VALUES = [1, 2, 3, 4, 5, 6, 7, 8, 9]
JOBCAT_VALUES = [1, 2, 3, 4, 5, 6]
OBSTYPE_VALUES = [1, 2, 3, 4]
NUMUNIT_VALUES = [1, 2, 3, 4, 5]
CONS_SOURCE_VALUES = [1001, 1002, 1003, 1004]
